fix: make profile picture layout responsive
MLH-Fellowship/jan-2022-prep-portfolio pull request #18
Opened 2022-01-11 14:36 UTC by CIPHERTron

This PR fixes #13 
@VaibhaveS and I have collaborated on fixing this issue.
- I've worked on fixing the CSS of the tablet view
- @VaibhaveS has worked on fixing the CSS of the mobile view
- What we did in order to fix it?
   - We used CSS grid and media queries for multiple breakpoints
   - Added some extra padding at the bottom of the pod name of `h1` type

### Attached Screenshots
<img width="829" alt="Screenshot 2022-01-11 at 8 20 56 PM" src="https://user-images.githubusercontent.com/56754747/148965592-4de41cd8-b1eb-4812-b2a9-ecb4bb8a95e9.png">

---

<img width="495" alt="Screenshot 2022-01-11 at 8 21 17 PM" src="https://user-images.githubusercontent.com/56754747/148965654-09cef4b4-f8e6-463b-9971-083aef7900aa.png">

---

<img width="378" alt="Screenshot 2022-01-11 at 8 22 18 PM" src="https://user-images.githubusercontent.com/56754747/148965671-d36328d0-97cc-42fb-ad2e-a88fb758cebd.png">

## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [X] I've explained what the Pull Request is adding.
- [X] I've explained why this is important.

2022-01-11 18:20 UTC, gmelodie commented on _sass/profile.scss
> +	}
Maybe trying to use 64-spaced tabs?

2022-01-11 18:23 UTC, Aniket762 commented on _sass/profile.scss
>  }
Looks Perfect!

2022-01-11 18:23 UTC, Aniket762 approved these changes

2022-01-11 21:29 UTC, yyjlincoln commented on _sass/profile.scss
> +	}
Hell yeah! 64-spaced tabs are the best

2022-01-11 21:31 UTC, yyjlincoln approved these changes
Perfect fix!

2022-01-12 23:28 UTC, yyjlincoln requested changes
Hey @CIPHERTron, I would like to merge it into `main`; however, it seems that the images are too big on desktops (especially if you have a big screen, the images are taking more than half of my screen). Can you please restrict the maximum size of the images?

[Here](https://github.com/yyjlincoln/_github_issues_assets/raw/master/0.png)'s a screenshot of the issue.

2022-01-13 03:33 UTC, CIPHERTron commented
> Hey @CIPHERTron, I would like to merge it into `main`; however, it seems that the images are too big on desktops (especially if you have a big screen, the images are taking more than half of my screen). Can you please restrict the maximum size of the images?
> 
> [Here](https://github.com/yyjlincoln/_github_issues_assets/raw/master/0.png)'s a screenshot of the issue.

Sure. Will do!

2022-01-13 03:50 UTC, CIPHERTron commented
@yyjlincoln do we require the screenshot that you've added to the repo? Since we're done with the issue, I think we can remove it 🤔

2022-01-13 03:52 UTC, yyjlincoln commented
> @yyjlincoln do we require the screenshot that you've added to the repo? Since we're done with the issue, I think we can remove it 🤔

Nope, we don't need that screenshot anymore. I didn't add it to the repo - that screenshot is actually hosted under my repo, `yyjlincoln/_github_issues_assets` and I will remove it shortly. Thanks though.

2022-01-13 04:00 UTC, yyjlincoln commented
@CIPHERTron The issue is still there... Do you want to double-check?
I tried cloning your repo/netlify preview and neither of them worked.

2022-01-13 04:03 UTC, CIPHERTron commented
@yyjlincoln 
Earlier it was taking 100% width and height of the parent div but now it only takes 93%. 90% will also look okay but reducing it further will increase the grid gap and will also look very small


<img width="1418" alt="Screenshot 2022-01-13 at 9 31 32 AM" src="https://user-images.githubusercontent.com/56754747/149263739-e047ce72-1c63-4698-b727-c8c6f88b30a7.png">

2022-01-13 04:04 UTC, yyjlincoln commented
Interesting... I will give it a try

2022-01-13 04:07 UTC, CIPHERTron commented
> Interesting... I will give it a try. The previous commit made no difference on my side

Maybe it's your cache 😅 
Try again with a hard reload. If that doesn't work, I'll look into it.

Also, should we change the profile images from 4 in a row to 5 in a row?

2022-01-13 04:10 UTC, yyjlincoln commented
I think a better way to do it is through `flex` which automatically goes to the next line when it overflows (instead of defining `@media` tags which may be incompatible on larger screens unless you define a larger `@media` tag). I'll submit a commit and we can discuss.

2022-01-13 04:16 UTC, CIPHERTron commented
> I think a better way to do it is through `flex` which automatically goes to the next line when it overflows (instead of defining `@media` tags which may be incompatible on larger screens unless you define a larger `@media` tag). I'll submit a commit and we can discuss.

Oh, in that case, we can use the concept of `minmax`
We won't have to write media queries there

2022-01-13 04:41 UTC, yyjlincoln commented
@CIPHERTron I've pushed it to the repo. What do you think?

2022-01-13 05:53 UTC, CIPHERTron commented
> @CIPHERTron I've pushed it to the repo. What do you think? Is it working on your side?
LGTM 🎉

2022-01-13 09:12 UTC, yyjlincoln approved these changes
Nice!

2022-01-13 09:47 UTC, yyjlincoln commented
> Maybe it's your cache 😅

Just saw that... It wasn't as I cloned your repo in a separate folder and made sure I cleared all caches & opened in incognito mode. Anyway - it's now fixed.

2022-01-13 09:48 UTC, yyjlincoln commented
Merging into main as:
- At least two approvals
- Fixed outstanding issues raised
- Passing all checks.

2022-01-13 09:48 UTC, merged