feat: Add pod blog
MLH-Fellowship/jan-2022-prep-portfolio pull request #54
Opened 2022-01-14 13:35 UTC by ditsuke

Closes #5. WIP

## Please, go through these steps before you submit a PR.

- [x] My Pod Leader knows I'm working on this Pull Request
- [x] I've explained what the Pull Request is adding.
- [x] I've explained why this is important.

2022-01-14 13:53 UTC, KhudaDad414 commented
@ditsuke hey, I think you link the wrong issue.

2022-01-14 13:56 UTC, ditsuke commented
> @ditsuke hey, I think you link the wrong issue.

Whoops, fixed!

2022-01-14 17:32 UTC, harshsharma6401 commented
There are no blogs added yet. Need any help ?

2022-01-14 17:52 UTC, psahithireddy commented
@harshsharma6401 we just made pages and displays, anyone can add blogs at any time (guess that was the goal). Currently, we made a template for 2 blogs, which we can easily extend,.@ditsuke I guess we will add instructions to add a blog in readme or maybe they can start an issue and tag us.

2022-01-14 20:30 UTC, harshsharma6401 commented
> @harshsharma6401 we just made pages and displays, anyone can add blogs at any time (guess that was the goal). Currently, we made a template for 2 blogs, which we can easily extend,.@ditsuke I guess we will add instructions to add a blog in readme or maybe they can start an issue and tag us.

Gotcha!

2022-01-15 14:09 UTC, ditsuke commented
Ready for review!

2022-01-16 00:41 UTC, yyjlincoln requested changes
Great work! Please check the comments.

2022-01-16 00:41 UTC, yyjlincoln commented on _layouts/blog.html
> +            </div>
You seem to be using the default layout & adding a custom banner here - which was what `projects.html` did. Can you try and use layout: page (which has the unified nav bar etc) to ensure consistent layout?

Not sure how you can deal with `{{page.author}}` though. Probably add a `{{ page.subtitle }}` in `_layouts/page.html` (and a if statement in HTML)? That way, pages without `subtitle` will also work as expected.

2022-01-16 00:41 UTC, yyjlincoln commented on _layouts/default.html
> -{% include toggle.html %}
Please don't change this file unnecessarily - it seems that this change will break a lot of pages.

2022-01-16 00:41 UTC, yyjlincoln commented on _layouts/default.html
> -{% include toggle.html %}
Is there a reason for this change?

2022-01-16 00:41 UTC, yyjlincoln commented on index.html
> +    </main>
Can't remember the exact reason why we used `.main-content` (probably javascript-related issues?) but I believe we used it for a reason (#24). I do understand that `<main>` is cleaner than `.main-content` but let's keep it as `.main-content` for now & we'll start another PR to change it to `.main-content` later. Thanks.

2022-01-16 00:42 UTC, yyjlincoln commented
Everything else looks great!

2022-01-16 07:46 UTC, ditsuke commented on _layouts/default.html
> -{% include toggle.html %}
I believe this was for improving the layout semantics. Looking at it again, I believe these changes are beyond the scope of this PR. I'll be reverting the relevant commit and using it in another PR!

2022-01-16 08:14 UTC, yyjlincoln approved these changes
LGTM! Thanks a lot. We can start another PR to improve layout semantics.
It would be great if you can fix the banner issue as well but that's not a requirement - I'm fine with both. I thought it would look better.

2022-01-16 08:15 UTC, yyjlincoln commented
Got my booster shot today so I'm really tired. I've also worked a bit too hard in the last week so I've decided to take a break on the weekends. Sorry that I couldn't help much today :(.

2022-01-16 08:21 UTC, ditsuke commented on _layouts/blog.html
> +            </div>
We use now the navbar with 0c98638!

2022-01-16 08:24 UTC, ditsuke commented
> Got my booster shot yesterday so I'm really tired. I've also worked a bit too hard in the last week so I decided to take a break on the weekends. Sorry that I couldn't help much today :(.

Thanks for approving Lincoln! Glad to hear you got the booster shot. You totally deserve the rest on weekends: you rocked and pulled more than your weight on weekdays and I definitely don't endorse working on weekends. Take care and hope you're good as new soon!

2022-01-16 11:03 UTC, yyjlincoln commented
LGTM! We can merge it if we can get another approval

2022-01-16 19:11 UTC, Dhruv-Sachdev1313 approved these changes
Looks Great!!

2022-01-16 19:29 UTC, ditsuke commented
2 approvals and passing checks - merging! thanks everyone

2022-01-16 19:29 UTC, merged